from pathlib import Path

# Base folder of this report tool
BASE_DIR = Path(__file__).resolve().parent

# Input JSON file generated by audit_permissions.py
# Change this value when you want to process another JSON file.
INPUT_JSON = BASE_DIR / "input_json" / "audit_permissions_20260614_233537.json"

# Output PDF folder
OUTPUT_DIR = BASE_DIR / "output_pdf"

# Company/report labels
REPORT_TITLE = "Permission Audit Compliance Report"
COMPANY_NAME = "TRANSTRACK"
REPORT_OWNER = "Data Governance / Security Audit"

# Visual settings
PRIMARY_COLOR = "#0B1F33"
ACCENT_COLOR = "#1F7A5A"
WARNING_COLOR = "#B7791F"
DANGER_COLOR = "#B42318"
LIGHT_BG = "#F4F6F8"
