"""
Permission Audit PDF Report Generator

Reads the JSON generated by audit_permissions.py and creates a professional PDF
that can be archived as audit evidence.
"""

import argparse
import json
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import LETTER, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether,
    NextPageTemplate,
)
from reportlab.pdfbase.pdfmetrics import stringWidth

from config_report import (
    INPUT_JSON,
    OUTPUT_DIR,
    COMPANY_NAME,
    REPORT_TITLE,
    REPORT_OWNER,
    PRIMARY_COLOR,
    ACCENT_COLOR,
    WARNING_COLOR,
    DANGER_COLOR,
    LIGHT_BG,
)


def hex_color(value: str):
    return colors.HexColor(value)


PRIMARY = hex_color(PRIMARY_COLOR)
ACCENT = hex_color(ACCENT_COLOR)
WARNING = hex_color(WARNING_COLOR)
DANGER = hex_color(DANGER_COLOR)
LIGHT = hex_color(LIGHT_BG)


def load_json(path: Path) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def safe(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


def shorten(value: Any, max_len: int = 70) -> str:
    text = safe(value)
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."


def status_color(status: str):
    status = (status or "").upper()
    if status == "GREEN":
        return ACCENT
    if status == "YELLOW":
        return WARNING
    if status == "RED":
        return DANGER
    return colors.gray


def build_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="CoverTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=26,
        leading=32,
        textColor=PRIMARY,
        alignment=TA_CENTER,
        spaceAfter=18,
    ))
    styles.add(ParagraphStyle(
        name="CoverSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#4A5568"),
        alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        name="H1Custom",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=19,
        textColor=PRIMARY,
        spaceBefore=10,
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        name="H2Custom",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=PRIMARY,
        spaceBefore=8,
        spaceAfter=5,
    ))
    styles.add(ParagraphStyle(
        name="BodyCustom",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#1F2937"),
        alignment=TA_LEFT,
    ))
    styles.add(ParagraphStyle(
        name="SmallCustom",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=7,
        leading=9,
        textColor=colors.HexColor("#4B5563"),
    ))
    styles.add(ParagraphStyle(
        name="MetricNumber",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        alignment=TA_CENTER,
        textColor=PRIMARY,
    ))
    styles.add(ParagraphStyle(
        name="MetricLabel",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=10,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#4B5563"),
    ))
    return styles


STYLES = build_styles()


def p(text: Any, style: str = "BodyCustom") -> Paragraph:
    return Paragraph(safe(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"), STYLES[style])


def footer(canvas, doc):
    canvas.saveState()
    width, height = LETTER
    canvas.setStrokeColor(colors.HexColor("#D9DEE3"))
    canvas.line(0.6 * inch, 0.55 * inch, width - 0.6 * inch, 0.55 * inch)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#6B7280"))
    canvas.drawString(0.6 * inch, 0.35 * inch, f"{COMPANY_NAME} - {REPORT_TITLE}")
    canvas.drawRightString(width - 0.6 * inch, 0.35 * inch, f"Page {doc.page}")
    canvas.restoreState()


def cover_page(canvas, doc):
    canvas.saveState()
    width, height = LETTER
    canvas.setFillColor(PRIMARY)
    canvas.rect(0, height - 1.2 * inch, width, 1.2 * inch, fill=1, stroke=0)
    canvas.setFillColor(ACCENT)
    canvas.rect(0, height - 1.28 * inch, width, 0.08 * inch, fill=1, stroke=0)
    canvas.restoreState()
    footer(canvas, doc)


def make_doc(output_path: Path) -> BaseDocTemplate:
    doc = BaseDocTemplate(
        str(output_path),
        pagesize=LETTER,
        leftMargin=0.55 * inch,
        rightMargin=0.55 * inch,
        topMargin=0.65 * inch,
        bottomMargin=0.65 * inch,
        title=REPORT_TITLE,
        author=REPORT_OWNER,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="normal")
    doc.addPageTemplates([
        PageTemplate(id="cover", frames=frame, onPage=cover_page),
        PageTemplate(id="normal", frames=frame, onPage=footer),
    ])
    return doc


def table(data, col_widths=None, font_size=7, header_bg=PRIMARY, repeat_rows=1):
    tbl = Table(data, colWidths=col_widths, repeatRows=repeat_rows, hAlign="LEFT")
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), header_bg),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), font_size),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("TEXTCOLOR", (0, 1), (-1, -1), colors.HexColor("#1F2937")),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D9DEE3")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return tbl


def metric_box(label: str, value: Any, bg=LIGHT):
    data = [[p(value, "MetricNumber")], [p(label, "MetricLabel")]]
    t = Table(data, colWidths=[1.65 * inch], rowHeights=[0.38 * inch, 0.24 * inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), bg),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D9DEE3")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    return t


def build_report_elements(payload: Dict[str, Any]) -> List[Any]:
    story: List[Any] = []
    meta = payload.get("metadata", {})
    summary = payload.get("summary", {})
    findings = payload.get("permission_compliance_findings", [])
    roles = payload.get("role_membership_inventory", {})
    classification = payload.get("data_classification_inventory", [])
    recommendations = payload.get("recommendations", [])

    overall = safe(summary.get("overall_status", "UNKNOWN")).upper()
    overall_bg = colors.HexColor("#FEF3C7") if overall == "YELLOW" else colors.HexColor("#DCFCE7") if overall == "GREEN" else colors.HexColor("#FEE2E2")

    # Cover
    story.append(Spacer(1, 1.1 * inch))
    story.append(p(COMPANY_NAME, "CoverSubtitle"))
    story.append(p(REPORT_TITLE, "CoverTitle"))
    story.append(p("Audit evidence generated from the JSON output of the permission audit process.", "CoverSubtitle"))
    story.append(Spacer(1, 0.35 * inch))
    story.append(table([
        ["Field", "Value"],
        ["Generated At", meta.get("generated_at", "")],
        ["Server", meta.get("server", "")],
        ["Database", meta.get("database", "")],
        ["Overall Status", overall],
        ["Log File", meta.get("log_file", "")],
    ], col_widths=[1.6 * inch, 4.6 * inch], font_size=8, header_bg=PRIMARY))
    story.append(Spacer(1, 0.25 * inch))
    story.append(table([[p("Audit Conclusion", "H2Custom")], [p(summary.get("message", ""), "BodyCustom")]], col_widths=[6.2 * inch], font_size=8, header_bg=status_color(overall)))
    story.append(NextPageTemplate("normal"))
    story.append(PageBreak())

    # Executive summary
    story.append(p("1. Executive Summary", "H1Custom"))
    story.append(p("This section summarizes the result of the permission audit for business, governance, security, and compliance stakeholders.", "BodyCustom"))
    story.append(Spacer(1, 0.12 * inch))
    metrics = Table([[metric_box("Total Findings", summary.get("total_findings_evaluated", 0)), metric_box("Compliant", summary.get("green", 0)), metric_box("Needs Review", summary.get("yellow", 0), colors.HexColor("#FEF3C7")), metric_box("Violations", summary.get("red", 0), colors.HexColor("#FEE2E2"))]], colWidths=[1.7 * inch] * 4)
    metrics.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")]))
    story.append(metrics)
    story.append(Spacer(1, 0.18 * inch))
    action_text = "Review yellow findings with Domain Owners. Remediate red findings immediately." if overall != "GREEN" else "Archive report as audit evidence."
    story.append(table([
        ["Overall Status", "Business Meaning", "Required Action"],
        [p(overall), p(summary.get("message", "")), p(action_text)],
    ], col_widths=[1.2 * inch, 3.1 * inch, 2.4 * inch], font_size=8, header_bg=status_color(overall)))

    # Findings by status/classification
    story.append(Spacer(1, 0.2 * inch))
    story.append(p("2. Findings Overview", "H1Custom"))
    by_status = Counter(f.get("status", "UNKNOWN") for f in findings)
    by_class = Counter(f.get("classification", "UNKNOWN") for f in findings)
    overview_rows = [["Category", "Count"]] + [[k, v] for k, v in by_status.items()] + [[f"Classification: {k}", v] for k, v in by_class.items()]
    story.append(table(overview_rows, col_widths=[4.8 * inch, 1.0 * inch], font_size=8))

    # Permission compliance findings
    story.append(Spacer(1, 0.2 * inch))
    story.append(p("3. Permission Compliance Findings", "H1Custom"))
    story.append(p("Each row represents a permission condition evaluated against the governance authorization model.", "BodyCustom"))
    finding_rows = [["Status", "Table", "Classification", "Permission", "Role", "User"]]
    for f in findings:
        finding_rows.append([
            f.get("status", ""),
            f.get("table", ""),
            f.get("classification", ""),
            f.get("permission", ""),
            f.get("role", ""),
            f.get("user", ""),
        ])
    story.append(table(finding_rows, col_widths=[0.75 * inch, 1.35 * inch, 1.35 * inch, 1.35 * inch, 0.85 * inch, 0.85 * inch], font_size=6.5))

    # Recommendations
    story.append(PageBreak())
    story.append(p("4. Recommended Actions", "H1Custom"))
    story.append(p("These recommendations are generated from the audit result and should be assigned to the appropriate Data Owner, Security Officer, DBA, or Governance Council depending on severity.", "BodyCustom"))
    rec_rows = [["Severity", "Action", "Table", "Classification", "Recommendation"]]
    for r in recommendations:
        rec_rows.append([
            p(r.get("severity", "")),
            p(r.get("action", "")),
            p(r.get("table", "")),
            p(r.get("classification", "")),
            p(shorten(r.get("message", ""), 95)),
        ])
    if len(rec_rows) == 1:
        rec_rows.append(["GREEN", "ARCHIVE", "N/A", "N/A", "No remediation action required."])
    story.append(table(rec_rows, col_widths=[0.75 * inch, 1.25 * inch, 1.15 * inch, 1.3 * inch, 2.2 * inch], font_size=6.5))

    # Role inventory
    story.append(Spacer(1, 0.2 * inch))
    story.append(p("5. Role Membership Inventory", "H1Custom"))
    role_rows = [["Role", "Member", "Principal Type", "Created Date"]]
    for role_name, members in roles.items():
        for m in members:
            role_rows.append([role_name, m.get("member_name", ""), m.get("principal_type", ""), safe(m.get("created_date", ""))[:19]])
    story.append(table(role_rows, col_widths=[1.45 * inch, 1.45 * inch, 1.4 * inch, 2.1 * inch], font_size=7))

    # Data classification inventory summarized and detailed
    story.append(PageBreak())
    story.append(p("6. Data Classification Inventory", "H1Custom"))
    story.append(p("This inventory lists sensitive columns detected by the audit source JSON. It supports traceability between classification policy and permission review.", "BodyCustom"))
    class_by_table = defaultdict(lambda: Counter())
    for item in classification:
        class_by_table[item.get("table_name", "UNKNOWN")][item.get("classification_level", "UNKNOWN")] += 1
    class_summary = [["Table", "PII Columns", "Financial Critical Columns", "Total Sensitive Columns"]]
    for table_name in sorted(class_by_table):
        c = class_by_table[table_name]
        class_summary.append([table_name, c.get("PII", 0), c.get("FINANCIAL_CRITICAL", 0), sum(c.values())])
    story.append(table(class_summary, col_widths=[2.4 * inch, 1.25 * inch, 1.8 * inch, 1.25 * inch], font_size=7))

    story.append(Spacer(1, 0.18 * inch))
    story.append(p("Detailed Classification Register", "H2Custom"))
    class_rows = [["Table", "Column", "Classification", "Information Type", "Audit Log"]]
    for item in classification:
        class_rows.append([
            item.get("table_name", ""),
            item.get("column_name", ""),
            item.get("classification_level", ""),
            shorten(item.get("information_type", ""), 45),
            safe(item.get("requires_audit_log", "")),
        ])
    story.append(table(class_rows, col_widths=[1.15 * inch, 1.35 * inch, 1.35 * inch, 2.0 * inch, 0.65 * inch], font_size=5.8))

    # Appendix
    story.append(PageBreak())
    story.append(p("7. Archival Evidence Notes", "H1Custom"))
    story.append(table([
        ["Evidence Item", "Value"],
        ["JSON Source System", meta.get("system", "")],
        ["JSON Report Type", meta.get("report_type", "")],
        ["Generated At", meta.get("generated_at", "")],
        ["Server", meta.get("server", "")],
        ["Database", meta.get("database", "")],
        ["Log File", meta.get("log_file", "")],
    ], col_widths=[2.0 * inch, 4.3 * inch], font_size=8))
    story.append(Spacer(1, 0.15 * inch))
    story.append(p("This PDF is generated from the canonical JSON output. The JSON should be retained with the PDF as machine-readable audit evidence.", "BodyCustom"))
    return story


def default_output_name(payload: Dict[str, Any]) -> str:
    meta = payload.get("metadata", {})
    generated = safe(meta.get("generated_at", "")).replace(":", "").replace(" ", "_").replace("UTC", "").strip("_")
    if not generated:
        generated = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    return f"permission_audit_report_{generated}.pdf"


def generate_pdf(input_json: Path, output_pdf: Path = None) -> Path:
    payload = load_json(input_json)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    if output_pdf is None:
        output_pdf = OUTPUT_DIR / default_output_name(payload)
    else:
        output_pdf = Path(output_pdf)
        output_pdf.parent.mkdir(parents=True, exist_ok=True)

    doc = make_doc(output_pdf)
    story = build_report_elements(payload)
    doc.build(story)
    return output_pdf


def main():
    parser = argparse.ArgumentParser(description="Generate a professional PDF from audit_permissions JSON output.")
    parser.add_argument("--input", "-i", default=str(INPUT_JSON), help="Path to audit JSON file")
    parser.add_argument("--output", "-o", default=None, help="Path to output PDF file")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        raise FileNotFoundError(f"Input JSON not found: {input_path}")

    output_path = generate_pdf(input_path, Path(args.output) if args.output else None)
    print(f"PDF report generated: {output_path}")


if __name__ == "__main__":
    main()
